extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 512
  batch:
    send_batch_size: 8192
    timeout: 5s

exporters:
  clickhousetraces:
    datasource: tcp://clickhouse:9000?password=Rayanparsi1900y
    use_new_schema: true
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000?password=Rayanparsi1900y
    database: signoz_metrics
  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs?password=Rayanparsi1900y
    timeout: 10s
  metadataexporter:
    dsn: tcp://clickhouse:9000/signoz_metadata?password=Rayanparsi1900y
    timeout: 10s
    tenant_id: default
    cache:
      provider: in_memory


service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [signozclickhousemetrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouselogsexporter]